const initialPortalsState = [
  {
    X: 21,
    Y: 96,
    name: "Lost Woods Pillar Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 174,
    Y: 38,
    name: "Rosso's House",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 251,
    Y: 79,
    name: "Death Montain West Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 405,
    Y: 19,
    name: "Floating Island Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 372,
    Y: 91,
    name: "Rosso's Ore Mine Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 236,
    Y: 142,
    name: "Sanctuary Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 355,
    Y: 135,
    name: "Waterfall Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 467,
    Y: 184,
    name: "Zora's Domain Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 90,
    Y: 208,
    name: "Sahasrala's House Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 54,
    Y: 270,
    name: "Stylish Woman Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 254,
    Y: 194,
    name: "Inside Hyrule Castle",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 349,
    Y: 274,
    name: "Eastern Pillar Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 402,
    Y: 352,
    name: "River Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 450,
    Y: 327,
    name: "Eastern Ruins SE Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 281,
    Y: 359,
    name: "Your House Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 237,
    Y: 390,
    name: "Swamp Pillar Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 475,
    Y: 384,
    name: "Hyrule Hotfoot Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 334,
    Y: 462,
    name: "Lake Hylia Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 166,
    Y: 426,
    name: "Paradox Hyrule Right Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 146,
    Y: 431,
    name: "Paradox Hyrule Left Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 162,
    Y: 462,
    name: "Misery Mire Entrance Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 104,
    Y: 435,
    name: "Desert Pillar Right Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 85,
    Y: 435,
    name: "Desert Pillar Left Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 75,
    Y: 386,
    name: "Desert North Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 59,
    Y: 465,
    name: "Desert Middle Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 16,
    Y: 490,
    name: "Desert SW Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 42,
    Y: 383,
    name: "Desert Palace Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 283,
    Y: 142,
    name: "Graveyard Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 533,
    Y: 96,
    name: "Skull Woods Pillar Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 686,
    Y: 38,
    name: "Destroyed House",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 763,
    Y: 79,
    name: "Lorule Death Montain West Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 917,
    Y: 19,
    name: "Lorule Floating Island Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 884,
    Y: 91,
    name: "Lorule Rosso's Ore Mine Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 748,
    Y: 142,
    name: "Philosopher's Cave Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 867,
    Y: 135,
    name: "Lorule Waterfall Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 979,
    Y: 184,
    name: "Ku's Domain Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 602,
    Y: 208,
    name: "n-Shaped House Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 566,
    Y: 270,
    name: "Thieves's Town Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 766,
    Y: 194,
    name: "Lorule Castle Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 861,
    Y: 274,
    name: "Dark Pillar Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 914,
    Y: 352,
    name: "Lorule River Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 962,
    Y: 327,
    name: "Dark Ruins SE Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 793,
    Y: 359,
    name: "Vacant House Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 749,
    Y: 390,
    name: "Lorule Swamp Pillar Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 987,
    Y: 384,
    name: "Lorule Hotfoot Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 846,
    Y: 462,
    name: "Lorule Lake Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 678,
    Y: 426,
    name: "Paradox Lorule Right Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 658,
    Y: 431,
    name: "Paradox Lorule Left Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 674,
    Y: 462,
    name: "Misery Mire Exit Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 616,
    Y: 435,
    name: "Misery Mire Pillar Right Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 597,
    Y: 435,
    name: "Misery Mire Pillar Left Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 587,
    Y: 386,
    name: "Misery Mire North Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 571,
    Y: 465,
    name: "Misery Mire Middle Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 528,
    Y: 490,
    name: "Misery Mire SW Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 554,
    Y: 383,
    name: "Zaganaga Crack",
    enabled: false,
    linkedIndex: null,
  },
  {
    X: 795,
    Y: 142,
    name: "Lorule Graveyard Crack",
    enabled: false,
    linkedIndex: null,
  },
];

export default initialPortalsState;
